using System.Collections;
using System.Collections.Generic;
using UnityEngine;
/**
 * This script controls collision checks for the Wormhole game object and assings a score value to its destruction based on the number generated by the seed in the game Controller script
 * 
 * */
public class CollisionCheckerWormhole : MonoBehaviour {
    private GameController gameController;
    public float ScoreValue;
    public GameObject Explosion;
    void Start()
    {
        GameObject gameControllerObject = GameObject.FindWithTag("GameController");
        if (gameControllerObject != null)
        {
            gameController = gameControllerObject.GetComponent<GameController>();
        }
        if (gameController == null)
        {
            // Debug.Log(" Cannot find Game Controller script");
        }
        ScoreValue = gameController.WormholeScore;
    }
    void OnCollisionEnter2D(Collision2D col)
    {
        //all projectile colliding game objects should be tagged "Enemy" or whatever in inspector but that tag must be reflected in the below if conditional
        if (col.gameObject.tag == "Player")
        {
           
            Destroy(col.gameObject);
        }
        else if(col.gameObject.tag == "Projectile")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "EnemyProjectile")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Hazard")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Power")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Speed")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Epic")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "PowerUp")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Enemy")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "EnemyShip")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "EnemyShipTwo")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "EnemyShipThree")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "PowerUpHealthUp")
        {
            Destroy(col.gameObject);
        }
        else if (col.gameObject.tag == "Laser")
        {
            gameController.WormholesDestroyedCounter++;
            Instantiate(Explosion, transform.position, transform.rotation);
            Destroy(gameObject);
            gameController.AddScore((int)ScoreValue);
        }
       
    }
}
